### ISSUE TITLE
Script locations are hardcoded

### ISSUE THREAD

**Issue by Tech-FZ** [arnavthorat78/ms-dos-mode#1]
Well, when making a video about this script, I noticed that it is hardcoded to the directory `C:\Users\arnav\Desktop\ms-dos-mode`. This is a problem because the majority of users aren't called Arnav and not everyone saves it to the desktop. Luckily, it's easy to fix.

**Comment by viradex** [comment]
It was used for testing; fixed now to default to `%systemroot%`.

**Comment by viradex** [comment]
Check commit [54346dd](https://github.com/arnavthorat78/ms-dos-mode/commit/54346dd38b1ae3cafbc6b389664044d9a95d2149).
